### PR TITLE
Add performance triage rotation

### PR DESCRIPTION
**Pull request by davidtwco**
Depends on rust-lang/calendar-generation#2.

### CODE REVIEW

**Comment by apiraino** [comment]
IIRC also @Kobzol is on rotation?

**Comment by davidtwco** [comment]
> IIRC also @Kobzol is on rotation?

I wasn't sure about this because the event in the old calendar for @Kobzol wasn't set to recur - but I'll add it now, apologies @Kobzol!

**Comment by Kobzol** [comment]
No problem :laughing: Thanks!

**Comment by davidtwco** [comment]
It's expected that the CI for this will fail until rust-lang/calendar-generation#2 is merged.

**Review by Mark-Simulacrum — APPROVED** [review]

**Pull request merged**
