### PR TITLE
Add compiler team backlog bonanza meeting

### PR DESCRIPTION
**Pull request by apiraino**
As per [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bplanning.5D.202024-05-24/near/440519331).

Hope the formatting of the event is correct. I'll amend, if not.

### CODE REVIEW

**Comment by apiraino** [comment]
@davidtwco would it be possible for me to have merge rights on this repository so I can quickly update the T-compiler .ics files with meetings?

Thanks

**Comment by spastorino** [comment]
Is this a recurring event?, if so is not tagged as one and if it's not there's no point in adding this as is a meeting that already happened.

**Comment by apiraino** [comment]
> Is this a recurring event?, if so is not tagged as one and if it's not there's no point anymore in adding this to the calendar as the meeting has already happened.

yeah, now it doesn't make a lot of sense anymore. My [question here](https://github.com/rust-lang/calendar/pull/54#issuecomment-2171270944) still stands, tho

**Comment by spastorino** [comment]
> > Is this a recurring event?, if so is not tagged as one and if it's not there's no point anymore in adding this to the calendar as the meeting has already happened.
> 
> yeah, now it doesn't make a lot of sense anymore. My [question here](https://github.com/rust-lang/calendar/pull/54#issuecomment-2171270944) still stands, tho

Just in case ... are you sure you don't have merge access? asking because I think I have merge access and hence you probably have too.

**Pull request closed without merging**
