### PR TITLE
Add tool to generate event UIDs and update README

### PR DESCRIPTION
**Pull request by traviscross**
According to the iCalendar (IETF) RFC 5545, the UID for each event must be "globally unique".  In this context, that means that the identifier must not collide with any other identifier for any other calendar event across all calendars, ever.

The way we were suggesting that people generate these, by calling out to `date`, unfortunately falls a bit short of being able to assure this.

Let's instead add a small tool to generate sufficiently-long randomly-generated identifiers to make it easy for people to do the right thing here for new events.

Merge this one after:

- https://github.com/rust-lang/calendar-generation/pull/15
- https://github.com/rust-lang/calendar/pull/66

cc @davidtwco

### CODE REVIEW

**Comment by apiraino** [comment]
Why not just suggest using `uuidgen` or any similar tool to generate UID (or UUID to be more precise)? We could spare dependencies and complexity to this tool :)

**Comment by traviscross** [comment]
Well, that's the idea here, is to spare dependencies so we don't need to ask people to install anything else.

This too isn't particularly complicated, and only depends on `getrandom`.

**Comment by apiraino** [comment]
I can't speak for many operating systems, but in Debian a UUID generator is marked as "required", in Fedora too (afaik). I think we can safely assume that it is installed *by default* everywhere? What's the dependency chain of `xtask` instead?

Anyway, just my .2 cents to avoid bloat.

**Comment by traviscross** [comment]
> What's the dependency chain of `xtask` instead?

Rust and `getrandom`, that's it.

**Review by davidtwco — APPROVED** [review]

**Comment by davidtwco** [comment]
Can you add a check/fmt/test for this utility in the CI?

**Pull request merged**
